### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by jiawei397** [KafkaSaur/KafkaSaur#1]
When I run the code, I met such a mistake：
```
Download https://deno.land/x/kafkasaur@v0.0.4/src/protocol/requests/AddPartitionsToTxn/index.ts
Download https://deno.land/x/kafkasaur@v0.0.4/src/protocol/requests/TxnOffsetCommit/index.ts
Download https://deno.land/x/kafkasaur@v0.0.4/src/protocol/requests/InitProducerId/index.ts
Download https://deno.land/x/kafkasaur@v0.0.4/src/protocol/requests/LeaveGroup/index.ts
error: Import 'https://deno.land/x/kafkasaur@v0.0.4/src/protocol/requests/AddPartitionsToTxn/index.ts' failed: 404 Not Found
    at https://deno.land/x/kafkasaur@v0.0.4/src/protocol/requests/index.ts:24:0
```
It seems like that the word `AddPartitionsToTxn` maybe Initial lowercase which is https://deno.land/x/kafkasaur@v0.0.4/src/protocol/requests/addPartitionsToTxn.

**Comment by samarnold723** [comment]
Thanks for opening this issue! And for trying KafkaSaur! We're excited you found us!

We've committed updated ESM import statements to main. Should work for you now. 

Thank you!

**Comment by jiawei397** [comment]
I was very happy to find it, because I was very sad to see that Kafka's maintainers said they were not going to develop the Deno version.
Unfortunately, the error is still reported this time. It is still a similar case problem:

```
error: Import 'https://deno.land/x/kafkasaur@v0.0.5/src/protocol/requests/LeaveGroup/index.ts' failed: 404 Not Found
    at https://deno.land/x/kafkasaur@v0.0.5/src/protocol/requests/index.ts:14:24

```

**Comment by samarnold723** [comment]
@jiawei397 thank you! Corrected this one as well! Thank you for spotting these!

**Comment by jiawei397** [comment]
Thanks for your reply. I found another bug and have submitted a merger application.
Thank you for developing the Deno version of Kafka, and then my project can be migrated from nodejs.
I hope the Deno community is getting better and better.
